# Generated by Django 2.2.2 on 2019-06-16 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_request', '0003_auto_20190612_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequest',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='request_status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Reviewed'), (3, 'Processed')], default=1),
        ),
    ]
