# Generated by Django 2.1.2 on 2019-06-12 13:26

import core.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='user',
            name='person_group',
            field=models.CharField(choices=[(1, 'Manage'), (2, 'Hr'), (3, 'Employee')], default=core.enums.PersonGroup(3), max_length=1),
        ),
    ]
