# Generated by Django 2.2.2 on 2019-06-12 16:29

import core.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190612_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='person_group',
            field=models.IntegerField(choices=[(1, 'Manage'), (2, 'Hr'), (3, 'Employee')], default=core.enums.PersonGroup(3)),
        ),
    ]
