# Generated by Django 2.2.2 on 2019-06-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190612_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='person_group',
            field=models.IntegerField(choices=[(1, 'Manage'), (2, 'Hr'), (3, 'Employee')], default=3),
        ),
    ]
