# Generated by Django 2.2.2 on 2019-06-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190615_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='person_group',
            field=models.IntegerField(choices=[(1, 'Employee'), (2, 'Hr'), (3, 'Manage')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
